# Copyright (c) 2020, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

title: "Jenkins in master-agent mode"
description: "Host Jenkins on Oracle Cloud Infrastructure to centralize your build automation and scale your deployment as the needs of your software projects grow."
stackDescription: "Jenkins in master-agent mode"
informationalText: "To connect to the Jenkins UI, copy jenkins_login_url and paste it to your web browser."
schemaVersion: 1.1.0
version: "20201028"
locale: "en"

variableGroups:
- title: "General Configuration"
  visible: false
  variables:
  - tenancy_ocid
  - region

- title: "Required Configuration"
  visible: true  
  variables:
  - compartment_ocid
  - availablity_domain_name 
  - jenkins_password

- title: "Optional Configuration"
  visible: true  
  variables:
  - plugins
  - vcn_cidr
  - label_prefix
  - lb_http_port
  - http_port
  - jnlp_port
  - jenkins_version
  - agent_count
  - instance_os
  - linux_os_version
  - bastion_display_name
  - bastion_shape
  - master_shape
  - agent_shape
  - bastion_user
  - listener_ca_certificate
  - listener_private_key
  - listener_public_certificate
  - release

variables:
  # General Configuration
  tenancy_ocid:
    title: "Tenancy ID"
    description: "The Oracle Cloud Identifier (OCID) for your tenancy"
    type: string
    required: true
    visibile: false

  region:
    title: "Region"
    description: "Region where you deploy your Jenkins"
    type: oci:identity:region:name
    required: true
    visibile: true

  compartment_ocid:
    title: "Compartment OCID"
    description: "Comparment where you deploy your Jenkins"
    type: oci:identity:compartment:id
    required: true
    visibile: true

  availablity_domain_name:
    type: oci:identity:availabilitydomain:name
    required: true
    visibile: true
    title: "Availability Domain to be chosen"
    description: "Choose Availability Domain where your Bastion will be deployed."
    dependsOn:
      regionName: ${region}
      compartmentId: ${compartment_ocid}

  jenkins_password:
    type: password
    default: ""
    required: true
    title: "Jenkins admin user password"
    description: "Enter password for Jenkins admin user"

  # Optional Configuration

  plugins:
    type: array
    items:
      type: string
      pattern: "^[a-zA-Z0-9\\-]+$"
    required: true
    title: "Jenkins Plugins"
    default: ["git","ssh-slaves","oracle-cloud-infrastructure-compute"]
    minItems: 1
    uniqueItems: true
    description: "Define Jenkins plugins to be installed (minimum 1 plugin)."

  vcn_cidr:
    type: string
    required: false
    default: "192.168.0.0/16"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "VCN CIDR"
    description: "A single, contiguous IPv4 CIDR block of your choice for the VCN"
  
  label_prefix:
    title: "Subnets' Label Prefix"
    description: "The Label Prefix for Jenkins subnets"
    type: string
    required: false

  lb_http_port:
    title: "Load Balanacer HTTP Port"
    description: "Load Balancer HTTP Port"
    default: 80
    minimum: 1
    maximum: 65535
    multipleOf: 1
    type: number
    required: false

  http_port:
    title: "HTTP Port"
    description: "HTTP Port for Jenkins Server"
    default: 8080
    minimum: 1
    maximum: 65535
    multipleOf: 1
    type: number
    required: false
  
  jnlp_port:
    title: "JNLP Port"
    description: "JNLP Port for Jenkins Server"
    default: 49187
    minimum: 1
    maximum: 65535
    multipleOf: 1
    type: number
    required: false

  jenkins_version:
    title: "Jenkins version"
    description: "Jenkins software version"
    default: "2.249.1"
    type: enum
    enum: 
      - "2.249.1"
    required: false

  agent_count:
    title: "Number of Jenkins Agent Servers"
    description: "Number of Jenkins Agent Servers"
    default: 2
    minimum: 2
    maximum: 1000
    multipleOf: 1
    type: number
    required: false

  instance_os:
    type: enum
    required: false
    visible: false
    title: "Instance OS"
    description: "An Operating System that determines the operating system for Jenkins host."
    default: "Oracle Linux"
    enum:
      - "Oracle Linux"

  linux_os_version:
    type: enum
    required: false
    visible: false
    title: "Instance OS version"
    description: "An Operating System version that determines the operating system version for Jenkins host."
    default: "7.8"
    enum:
      - "7.8" 

  bastion_display_name:
    title: "Name of Bastion Server"
    description: "Name of Bastion Server"
    default: "JenkinsBastion"
    type: string
    required: false

  bastion_shape:
    type: oci:core:instanceshape:name
    title: "Bastion Server Shape"
    description: "Bastion Server Shape"
    default: "VM.Standard2.1"
    required: false
    dependsOn:
      compartmentId: ${compartment_ocid}

  master_shape:
    type: oci:core:instanceshape:name
    title: "Jenkins Master Server Shape"
    description: "Jenkins Master Server Shape"
    default: "VM.Standard2.4"
    required: false
    dependsOn:
      compartmentId: ${compartment_ocid}

  agent_shape:
    type: oci:core:instanceshape:name
    title: "Jenkins Agent Server Shape"
    description: "Jenkins Agent Server Shape"
    default: "VM.Standard2.4"
    required: false
    dependsOn:
      compartmentId: ${compartment_ocid}

  bastion_user:
    type: string
    title: "Bastion Server OS User"
    description: "Bastion Server OS User"
    default: "opc"
    required: false
    visible: false

  listener_ca_certificate:
    type: text
    title: "Load Balanacer Listener CA Certificate"
    description: "Load Balanacer Listener CA Certificate"
    required: false
     
  listener_private_key:
    type: text
    title: "Load Balanacer Listener Private Key"
    description: "Load Balanacer Listener Private Key"
    required: false

  listener_public_certificate:
    type: text
    title: "Load Balanacer Listener Public Certificate"
    description: "Load Balanacer Listener Public Certificate"
    required: false
  
  release:
    type: string
    required: false
    visible: false
    title: "Reference Architecture Release (OCI Architecture Center)"

outputs:

  bastion_public_ip:
    title: "Bastion Server Public IP"
    displayText: "Bastion Server Public IP"
    type: copyableString
    visible: true

  jenkins_login_url:
    title: "Jenkins Login URL"
    displayText: "Jenkins Login URL"
    type: string
    visible: true
  
  generated_ssh_private_key:
    title: "Generated SSH Private Key"
    displayText: "Generated SSH Private Key"
    type: string
    visible: true
  
  master_private_ip:
    title: "Jenkins Master Private IP"
    displayText: "Jenkins Master Private IP"
    type: copyableString
    visible: true

  agent_private_ips:
    title: "Jenkins Agents Private IPs"
    displayText: "Jenkins Agents Private IPs"
    type: string
    visible: true

 

